### ISSUE TITLE
[Epic] Introduce emulator & Suite tests with Regtest

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#1076]
We desperately need emulator <-> Suite tests. After we have a new hire this is what I would like to focus on.

As a hotfix we can add Suite's tests. They already have [some tests](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/602202828) against our emulator so we could run these as well for every change.

In a long-term perspective I would like to:
- [x] Refactor Suite's [trezor-user-env](https://github.com/trezor/trezor-suite/tree/develop/docker/trezor-user-env).
- [x] Add an option to use number of older firmware emulators.
- [ ] Add an option to use number of older older trezorctls?
- [x] Separate into standalone repo/project?
- [x] Include Bitcoin.
  - This would be a game-changer, because we could test the whole ecosystem. Suite would send tx to emulator, that would sign it, suite would broadcast it into the network and bitcoind would mine it. This would also solve @andrewkozlik's point that we do not have valid transactions in device tests. Do we need blockbook as well?
  - [x] Add bitcoind and bitcoincli to the Docker image.
  - [x] Run regtest.
  - [x] Add commands to the websocket server creating blocks, mining etc.
- [x] Refactor the Python server.

Related: #115, #1018.

**Comment by tsusanka** [comment]
This is basically done, see https://github.com/trezor/trezor-user-env/issues/99. "All" that is needed now is to write the tests which is tracked elsewhere.
