### ISSUE TITLE
[meta] Future improvements of the boot process

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#12]
This is an issue to discuss future improvements of the boot process.

- [ ] update the firmware so it works with the original VTOR table from the bootloader
- [ ] update the firmware so it works in unprivileged mode, most probably enabling the supervisor calls will do the trick: https://github.com/trezor/trezor-mcu/pull/323
- [ ] create a mechanism so SIGNED firmware can indicate the bootloader it needs to use its own VTOR table and/or it needs privileged mode

**Comment by tsusanka** [comment]
@prusnak is this still up to date? Is it something we would like to include in the next bootloader release?

**Comment by tsusanka** [comment]
I am assigning @hiviah as well to assess this.

**Comment by matejcik** [comment]
alright, thanks.
pinging @prusnak in case we want to return to this, but for now I'm closing the issue.
