### ISSUE TITLE
TT Redesign

### ISSUE THREAD

**Issue by alex-jerechinsky** [trezor/trezor-firmware#1922]
Priority: Tasks that are required for Bitcoin only firmware

- [x] pagination
  - #1960 
  - #1961 
  - #1993 
- [x] #2118
- [x] enable debuglink for new UI
- [x] #2169
- [x] fonts #1122
- [ ] [clean up timer handling](https://github.com/trezor/trezor-firmware/pull/2227#discussion_r869337119): #2299
- [ ] implement layouts
  - [x] generic dialogs and confirmations
    - #2071
    - #2097
    - #2155
  - [x] #2215
  - [x] #2498 
  - [x] FIDO layouts #2532
  - [x] #2298
  - [x] #2142
    - #2098 
    - #2154
  - [ ] PIN/passphrase/recovery keyboard
    - #2104
    - #2154
    - #2227 
    - [x] fix visual glitches caused by overlapping `Maybe`s (needs Honza's placement code)
    - [x] show wrong pin warning (needs ability to start timer on layout init)
    - [x] long passphrases #2499
    - [ ] #2530
    - [x] funny button shape in PIN keyboard
  - [x] #2519
  - [x] altcoins #2500
- [x] `show_success` cannot break long lines, we need to add support for center-aligned paragraphs (in #2383)
- [x] #2531
- [x] `confirm_blob` doesn't support `ask_pagination` yet (bitcoin doesn't need it)
- [x] each icon (for IconDialog) takes 0.5K of flash, we need to either figure out how to represent three-color image more efficiently than 16bpp, or draw them procedurally
- [ ] unlocking and signing and verifying pin progress
- [x] fix device tests to work with UI2, possibly combined with dropping python UI entirely

Post-switch:
- [x] #2631
- [x] #2624 #2643
- [ ] #2629
- [ ] #2585
- [x] #2665 
- [x] #2670 
- [ ] rename `ui/layouts/tt_v2` to `tt`, merge and clean up `class Layout` + `class RustLayout`

Nice to have:
- [ ] switch to rust implementation of qrcodegen, this would make it possible to propagate errors to python which we currently don't do

**Comment by grdddj** [comment]
While getting rid of all `UI1` stuff as a part of https://github.com/trezor/trezor-firmware/issues/2559, I noticed that `ui.Component` is being used in couple `monero` layouts, for example
https://github.com/trezor/trezor-firmware/blob/ac6936d65d19d3cf2b1c2a6bfe86cd897583e4dc/core/src/apps/monero/layout.py#L183-L197

Could it be left as-is, or do we want to convert it into some `Rust` layout?

**Comment by matejcik** [comment]
the code above should be reworked completely, there is an issue #2217. I will write more in there.

**Comment by hynek-jina** [comment]
Generally done.. Remaining task has dedicated issues..
