### ISSUE TITLE
[epic] use Trezor without computer

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-firmware#265]
This is a list of issues that will allow to use Trezor without computer connected:

- [ ] https://github.com/trezor/trezor-firmware/issues/61 Simple on-device management
- [ ] https://github.com/trezor/trezor-firmware/issues/23 diceware/cointoss initialization
- [ ] https://github.com/trezor/trezor-firmware/issues/49 add support for PSBT (BIP-174)
- [ ] https://github.com/trezor/trezor-firmware/issues/60 bootloader: Add "Wipe device" button
<s>- [ ] https://github.com/trezor/trezor-firmware/issues/62 bootloader: Add flag to FW header for disabling "Connect to host"</s>
- [ ] https://github.com/trezor/trezor-firmware/issues/64 bootloader: Upload firmware over SD card

**Comment by Hannsek** [comment]
Moving to milestone: https://github.com/trezor/trezor-firmware/milestone/45.
