### ISSUE TITLE
[epic] STM32U5

### ISSUE THREAD

**Issue by TychoVrahe** [trezor/trezor-firmware#3405]
Collection of issues and PRs tracking the progress of STM32U5 implementation

```[tasklist]
### Tasks
- [ ] [basic support](https://github.com/trezor/trezor-firmware/pull/3370) (mcu init, periph drivers etc)
- [ ] [discovery kit support](https://github.com/trezor/trezor-firmware/pull/3370)
- [x] [stm32u585](https://github.com/trezor/trezor-firmware/pull/3404)
- [ ] sd card driver for U5 https://github.com/trezor/trezor-firmware/pull/3422
- [ ] [quadword only storage](https://github.com/trezor/trezor-firmware/pull/3228)
- [ ] https://github.com/trezor/trezor-firmware/pull/3346
- [ ] https://github.com/trezor/trezor-firmware/pull/3348
- [ ] https://github.com/trezor/trezor-firmware/pull/3406
- [ ] mark sensitive data to place them in ECC & tamper protected RAM
- [ ] integrate SAES to storage
- [ ] https://github.com/trezor/trezor-firmware/issues/3638
```
