### ISSUE TITLE
Improve EVM contract flow

### ISSUE THREAD

**Issue by ibz** [trezor/trezor-firmware#4302]
While implementing #4251 some shortcuts were taken. The flow does generally behave as it should, but it doesn't look exactly like Figma. This has to be fixed.

Some technical debt also needs to be taken care of:

```[tasklist]
- [x] stop using `confirm_blob` for warnings (and remove `default_cancel` on `confirm_blob`)
- [x] get rid of `confirm_blob_with_optional_pagination`
- [x] get rid of `description_font_green`
```

Tweaks to the flow:

```[tasklist]
### Tasks
- [x] TS5: show page number when paginating through input data
- [x] TS5: "X" when paginating through input data
- [x] TS5: "input data" - 1st page content is shorter
- [x] TS5: "input data" confirm footer
- [x] TS5: show data size on paginated data
- [x] TS3 & T: Unknown contract warning - different copy
- [x] TS3: paginated data - "continue" button instead of "go back"
- [x] TS3: "token contract" continue button
- [x] TS3: data size mismatch?
```
