### ISSUE TITLE
[Epic] Redesign UI

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#436]
Phase 1:
- [x] https://github.com/trezor/trezor-firmware/issues/434 Create a basic UI styleguide
- [ ] #1122 Implement new fonts
- [ ] #1123 UI support for T1 in Core
- [ ] #1124 Redesign pagination
... other to be added

Phase 2:
Make sure these were implemented:
- [ ] #435 Use common UI in apps
- [ ] https://github.com/trezor/trezor-firmware/issues/53 Revisit coins UI
