### ISSUE TITLE
[epic] Refactor and polish SLIP-39 UI and storage

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#442]
Refactoring:
- [x] Unify reset/recovery layouts (tracked in https://github.com/trezor/trezor-firmware/issues/409)
- [x] refactor management.common.layout (#456)
- [x] Improve storage.fetch function and maybe other groups-related storage functions. Also fetch could use fetch_groups?
- [x] Use show_success and show_warning everywhere (#456 and check everywhere else)

Functionality changes:
- [x] support 1of1 - #455 
- [x] Move check GroupThresholdReached and ShareAlreadyAdded Errors  - #457
- ~[ ] Introduce a function for plural strings - #447~ Deferred 
- [x] Store correct mnemonic type in load_device - #458
- [x] Skip threshold prompt if number of shares is 1. #463

Investigate and decide:
- [x] "Remaining shares screen" is confusing, discuss with UX and fix. #451 
- [x] Unify the usage of single vs group shamir - I believe we should have a single API for that, which works with the groups - #459
- [x] have a look at min/max allowed share/threshold/group values - #460, also relates to #455 
- [ ] Discuss: Should we allow the group count to be 1 in advanced backup?

Tests:
- [x] test improvements tracked in #462

Documentation:
- ~[ ] Add comment to RuntimeError in recovery_shares.py~ Runtime error was removed completely

**Comment by andrewkozlik** [comment]
- [ ] Skip threshold prompt if number of shares is 1.
- [ ] Discuss: Should we allow the group count to be 1 in advanced backup?

**Comment by andrewkozlik** [comment]
- [ ] It would be nice to unify the naming of the constants and variables for advanced (group) shamir backup. Currently we have:
  - advanced_shamir true vs. false
  - Slip39_Single_Group vs. Slip39_Multiple_Groups
  - TYPE_SLIP39 vs. TYPE_SLIP39_GROUP

**Comment by ciny** [comment]
@andrewkozlik 
1. created issue #463 
2. added as a topic for discussion to this epic. no issue yet
3. referenced in #459, if you have other suggestions regarding single vs multi group shamir naming please add it there

**Comment by tsusanka** [comment]
Note to myself: Before doing a PR, I want to have a look at:
- [ ] _request_secret function
- [ ] mypy
