### ISSUE TITLE
[Epic] Improve documentation

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#685]
Let's improve our documentation.

Firstly, we should extend mdBook on the whole monorepo not just the core/ section. https://github.com/trezor/trezor-firmware/issues/686

---

We have agreed we are writing documentation for five roles:
1. Someone integrating Trezor who wants more info about connect or trezorlib.
- [ ] https://github.com/trezor/trezor-firmware/issues/229 Document trezorlib API
2. Someone who wishes to contribute to trezor-firmware.
- [ ]  #687 Check and document how to build
- [ ]  #688 Check and document how to run emulators 
- [ ]  #689 Check and document how to run tests
- [ ]  #690 Document protobuf communication
- [ ]  #691 Document how to contribute to core using an example feature
3. Someone who builds Trezor's software themselves (reproducible build).
- [ ]  #692 Check and document reproducible builds
4. Someone who builds Trezor including hardware (aka DYI).
- [ ]  #693 Check and document hardware
5. Hard core "nerds" - detailed information about storage, used cryptography etc.
- [ ]  #693 Check and document storage and trezor-crypto

**Comment by hynek-jina** [comment]
Epic migrated to separate Milestone:
https://github.com/trezor/trezor-firmware/milestone/35
