### ISSUE TITLE
[Epic] Firmware translations (localisation)

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-firmware#987]
We would like to translate both T1 and TT firmwares to help onboard non-English users. We will first tackle this in Core, if _porting_ goes well, we will achieve this in T1 using the Core codebase.

What is most likely obvious but seems better to write it explicitly is that a incorrect translation could lead to a security issue where the user is confirming a different action than intended. We need to be careful.

## List of sub-issues: 

_Slightly in order what needs to achieved first._

- [x] Investigate newlines in layouts #1005 
- [x] Design signed data blob in storage #988
- [ ] Replace all English strings with identifiers and collect them #991 
- [ ] Figure out translations data blob signing process #1016
- [ ] Implement data blob exchange mechanism #1017 
- [ ] Translate wire errors #1006
- [x] Create a simple webapp mimicking Trezor screen #993
- [ ] Translate bootloader #994
- [ ] Create a Translations report on CI #992
- [ ] Submit strings collection to Crowdin #1019

**Comment by mmilata** [comment]
Note: depending on the chosen languages we might have to add additional characters to our fonts.

**Comment by Hannsek** [comment]
We are moving to the milestone https://github.com/trezor/trezor-firmware/milestone/40
